// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("statsig");

/**
 * A Statsig Console API Key
 */
export declare const consoleApiKey: string | undefined;
Object.defineProperty(exports, "consoleApiKey", {
    get() {
        return __config.get("consoleApiKey");
    },
    enumerable: true,
});

