// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Statsig.Pulumi.Outputs
{

    [OutputType]
    public sealed class EntityPropertyIdTypeMapping
    {
        /// <summary>
        /// Column name linked to the ID.
        /// </summary>
        public readonly string Column;
        /// <summary>
        /// ID for the Statsig unit.
        /// </summary>
        public readonly string StatsigUnitId;

        [OutputConstructor]
        private EntityPropertyIdTypeMapping(
            string column,

            string statsigUnitId)
        {
            Column = column;
            StatsigUnitId = statsigUnitId;
        }
    }
}
