// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Statsig.Outputs
{

    [OutputType]
    public sealed class ExperimentGroup
    {
        public readonly string? Description;
        public readonly bool? Disabled;
        public readonly string? ForeignGroupId;
        public readonly string? Id;
        public readonly string Name;
        public readonly ImmutableDictionary<string, string> ParameterValues;
        public readonly double Size;

        [OutputConstructor]
        private ExperimentGroup(
            string? description,

            bool? disabled,

            string? foreignGroupId,

            string? id,

            string name,

            ImmutableDictionary<string, string> parameterValues,

            double size)
        {
            Description = description;
            Disabled = disabled;
            ForeignGroupId = foreignGroupId;
            Id = id;
            Name = name;
            ParameterValues = parameterValues;
            Size = size;
        }
    }
}
