// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Statsig.Outputs
{

    [OutputType]
    public sealed class GateRuleCondition
    {
        public readonly string? CustomId;
        public readonly string? Field;
        public readonly string? Operator;
        public readonly ImmutableArray<string> TargetValues;
        public readonly string Type;

        [OutputConstructor]
        private GateRuleCondition(
            string? customId,

            string? field,

            string? @operator,

            ImmutableArray<string> targetValues,

            string type)
        {
            CustomId = customId;
            Field = field;
            Operator = @operator;
            TargetValues = targetValues;
            Type = type;
        }
    }
}
