// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Statsig.Pulumi.Outputs
{

    [OutputType]
    public sealed class GateRule
    {
        /// <summary>
        /// The base ID of this rule, i.e. without any added metadata. Will remain the exact same throughout
        /// </summary>
        public readonly string? BaseId;
        /// <summary>
        /// An array of Condition objects.
        /// </summary>
        public readonly ImmutableArray<Outputs.GateRuleCondition> Conditions;
        /// <summary>
        /// The environments this rule is enabled for.
        /// </summary>
        public readonly ImmutableArray<string> Environments;
        /// <summary>
        /// The Statsig ID of this rule.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The name of this rule.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Of the users that meet the conditions of this rule, what percent should return true.
        /// </summary>
        public readonly double PassPercentage;
        /// <summary>
        /// The return value of the rule.
        /// </summary>
        public readonly Outputs.GateRuleReturnValue? ReturnValue;

        [OutputConstructor]
        private GateRule(
            string? baseId,

            ImmutableArray<Outputs.GateRuleCondition> conditions,

            ImmutableArray<string> environments,

            string? id,

            string name,

            double passPercentage,

            Outputs.GateRuleReturnValue? returnValue)
        {
            BaseId = baseId;
            Conditions = conditions;
            Environments = environments;
            Id = id;
            Name = name;
            PassPercentage = passPercentage;
            ReturnValue = returnValue;
        }
    }
}
