// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Statsig.Outputs
{

    [OutputType]
    public sealed class MetricWarehouseNativeDenominatorCriteria
    {
        /// <summary>
        /// Optional column specifying which data attribute to filter on.
        /// </summary>
        public readonly string? Column;
        /// <summary>
        /// sql*filter, start*withs, ends*with, and after*exposure are only applicable in Warehouse Native
        /// </summary>
        public readonly string Condition;
        /// <summary>
        /// If true, overrides null values in criterion evaluation.
        /// </summary>
        public readonly bool? NullVacuousOverride;
        /// <summary>
        /// Type of event criterion for filtering metrics. Options include `value`, `metadata`, `user`, and `user_custom`; in Warehouse Native, this should always be `metadata`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Optional array of values for the criterion to match against.
        /// </summary>
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private MetricWarehouseNativeDenominatorCriteria(
            string? column,

            string condition,

            bool? nullVacuousOverride,

            string type,

            ImmutableArray<string> values)
        {
            Column = column;
            Condition = condition;
            NullVacuousOverride = nullVacuousOverride;
            Type = type;
            Values = values;
        }
    }
}
