// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Statsig.Pulumi.Outputs
{

    [OutputType]
    public sealed class MetricFunnelEventList
    {
        /// <summary>
        /// The name of the funnel event used in the metric.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The type of funnel event, specifying how the event is tracked.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private MetricFunnelEventList(
            string name,

            string type)
        {
            Name = name;
            Type = type;
        }
    }
}
