// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Statsig.Pulumi.Outputs
{

    [OutputType]
    public sealed class MetricSourceIdTypeMapping
    {
        /// <summary>
        /// The corresponding column name in the source that relates to the Statsig unit ID.
        /// </summary>
        public readonly string Column;
        /// <summary>
        /// The identifier mapping for Statsig units.
        /// </summary>
        public readonly string StatsigUnitId;

        [OutputConstructor]
        private MetricSourceIdTypeMapping(
            string column,

            string statsigUnitId)
        {
            Column = column;
            StatsigUnitId = statsigUnitId;
        }
    }
}
