// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Statsig.Outputs
{

    [OutputType]
    public sealed class MetricMetricEvent
    {
        /// <summary>
        /// Filtering criteria for the metric event, including conditions and values to refine the event data.
        /// </summary>
        public readonly ImmutableArray<Outputs.MetricMetricEventCriteria> Criterias;
        /// <summary>
        /// The key for associated metadata, if applicable.
        /// </summary>
        public readonly string? MetadataKey;
        /// <summary>
        /// The name of the metric event.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The type of metric event. Allowed values include: count, count_distinct, value, and metadata.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private MetricMetricEvent(
            ImmutableArray<Outputs.MetricMetricEventCriteria> criterias,

            string? metadataKey,

            string name,

            string? type)
        {
            Criterias = criterias;
            MetadataKey = metadataKey;
            Name = name;
            Type = type;
        }
    }
}
