// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Statsig.Outputs
{

    [OutputType]
    public sealed class MetricWarehouseNativeFunnelEvent
    {
        /// <summary>
        /// Optional array of criteria to filter the funnel events, defined by various types and conditions.
        /// </summary>
        public readonly ImmutableArray<Outputs.MetricWarehouseNativeFunnelEventCriteria> Criterias;
        /// <summary>
        /// Optional name of the metric source associated with the funnel event.
        /// </summary>
        public readonly string? MetricSourceName;
        /// <summary>
        /// Optional step name for the funnel event, can be null if not specified.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Name of column which being used as session identifier. Funnel event with the same metric source
        /// </summary>
        public readonly string? SessionIdentifierField;

        [OutputConstructor]
        private MetricWarehouseNativeFunnelEvent(
            ImmutableArray<Outputs.MetricWarehouseNativeFunnelEventCriteria> criterias,

            string? metricSourceName,

            string? name,

            string? sessionIdentifierField)
        {
            Criterias = criterias;
            MetricSourceName = metricSourceName;
            Name = name;
            SessionIdentifierField = sessionIdentifierField;
        }
    }
}
