// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Statsig.Inputs
{

    public sealed class EntityPropertyIdTypeMappingGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Column name linked to the ID.
        /// </summary>
        [Input("column", required: true)]
        public Input<string> Column { get; set; } = null!;

        /// <summary>
        /// ID for the Statsig unit.
        /// </summary>
        [Input("statsigUnitId", required: true)]
        public Input<string> StatsigUnitId { get; set; } = null!;

        public EntityPropertyIdTypeMappingGetArgs()
        {
        }
        public static new EntityPropertyIdTypeMappingGetArgs Empty => new EntityPropertyIdTypeMappingGetArgs();
    }
}
