// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Statsig.Pulumi.Inputs
{

    public sealed class ExperimentSecondaryMetricGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("direction")]
        public Input<string>? Direction { get; set; }

        [Input("hypothesizedValue")]
        public Input<double>? HypothesizedValue { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public ExperimentSecondaryMetricGetArgs()
        {
        }
        public static new ExperimentSecondaryMetricGetArgs Empty => new ExperimentSecondaryMetricGetArgs();
    }
}
