// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Statsig.Inputs
{

    public sealed class ExperimentGroupGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        [Input("foreignGroupId")]
        public Input<string>? ForeignGroupId { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("parameterValues", required: true)]
        private InputMap<string>? _parameterValues;
        public InputMap<string> ParameterValues
        {
            get => _parameterValues ?? (_parameterValues = new InputMap<string>());
            set => _parameterValues = value;
        }

        [Input("size", required: true)]
        public Input<double> Size { get; set; } = null!;

        public ExperimentGroupGetArgs()
        {
        }
        public static new ExperimentGroupGetArgs Empty => new ExperimentGroupGetArgs();
    }
}
