// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Statsig.Pulumi.Inputs
{

    public sealed class MetricMetricEventGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("criterias")]
        private InputList<Inputs.MetricMetricEventCriteriaGetArgs>? _criterias;

        /// <summary>
        /// Filtering criteria for the metric event, including conditions and values to refine the event data.
        /// </summary>
        public InputList<Inputs.MetricMetricEventCriteriaGetArgs> Criterias
        {
            get => _criterias ?? (_criterias = new InputList<Inputs.MetricMetricEventCriteriaGetArgs>());
            set => _criterias = value;
        }

        /// <summary>
        /// The key for associated metadata, if applicable.
        /// </summary>
        [Input("metadataKey")]
        public Input<string>? MetadataKey { get; set; }

        /// <summary>
        /// The name of the metric event.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The type of metric event. Allowed values include: count, count_distinct, value, and metadata.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public MetricMetricEventGetArgs()
        {
        }
        public static new MetricMetricEventGetArgs Empty => new MetricMetricEventGetArgs();
    }
}
