// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Statsig.Pulumi.Inputs
{

    public sealed class MetricWarehouseNativeCriteriaGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional column specifying which data attribute to filter on.
        /// </summary>
        [Input("column")]
        public Input<string>? Column { get; set; }

        /// <summary>
        /// sql*filter, start*withs, ends*with, and after*exposure are only applicable in Warehouse Native
        /// </summary>
        [Input("condition", required: true)]
        public Input<string> Condition { get; set; } = null!;

        /// <summary>
        /// If true, overrides null values in criterion evaluation.
        /// </summary>
        [Input("nullVacuousOverride")]
        public Input<bool>? NullVacuousOverride { get; set; }

        /// <summary>
        /// Type of event criterion for filtering metrics. Options include `value`, `metadata`, `user`, and `user_custom`; in Warehouse Native, this should always be `metadata`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("values")]
        private InputList<string>? _values;

        /// <summary>
        /// Optional array of values for the criterion to match against.
        /// </summary>
        public InputList<string> Values
        {
            get => _values ?? (_values = new InputList<string>());
            set => _values = value;
        }

        public MetricWarehouseNativeCriteriaGetArgs()
        {
        }
        public static new MetricWarehouseNativeCriteriaGetArgs Empty => new MetricWarehouseNativeCriteriaGetArgs();
    }
}
