// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Statsig.Inputs
{

    public sealed class MetricWarehouseNativeFunnelEventGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("criterias")]
        private InputList<Inputs.MetricWarehouseNativeFunnelEventCriteriaGetArgs>? _criterias;

        /// <summary>
        /// Optional array of criteria to filter the funnel events, defined by various types and conditions.
        /// </summary>
        public InputList<Inputs.MetricWarehouseNativeFunnelEventCriteriaGetArgs> Criterias
        {
            get => _criterias ?? (_criterias = new InputList<Inputs.MetricWarehouseNativeFunnelEventCriteriaGetArgs>());
            set => _criterias = value;
        }

        /// <summary>
        /// Optional name of the metric source associated with the funnel event.
        /// </summary>
        [Input("metricSourceName")]
        public Input<string>? MetricSourceName { get; set; }

        /// <summary>
        /// Optional step name for the funnel event, can be null if not specified.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Name of column which being used as session identifier. Funnel event with the same metric source
        /// </summary>
        [Input("sessionIdentifierField")]
        public Input<string>? SessionIdentifierField { get; set; }

        public MetricWarehouseNativeFunnelEventGetArgs()
        {
        }
        public static new MetricWarehouseNativeFunnelEventGetArgs Empty => new MetricWarehouseNativeFunnelEventGetArgs();
    }
}
