# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .entity_property import *
from .experiment import *
from .gate import *
from .keys import *
from .metric import *
from .metric_source import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_statsig.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_statsig.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "statsig",
  "mod": "index/entityProperty",
  "fqn": "pulumi_statsig",
  "classes": {
   "statsig:index/entityProperty:EntityProperty": "EntityProperty"
  }
 },
 {
  "pkg": "statsig",
  "mod": "index/experiment",
  "fqn": "pulumi_statsig",
  "classes": {
   "statsig:index/experiment:Experiment": "Experiment"
  }
 },
 {
  "pkg": "statsig",
  "mod": "index/gate",
  "fqn": "pulumi_statsig",
  "classes": {
   "statsig:index/gate:Gate": "Gate"
  }
 },
 {
  "pkg": "statsig",
  "mod": "index/keys",
  "fqn": "pulumi_statsig",
  "classes": {
   "statsig:index/keys:Keys": "Keys"
  }
 },
 {
  "pkg": "statsig",
  "mod": "index/metric",
  "fqn": "pulumi_statsig",
  "classes": {
   "statsig:index/metric:Metric": "Metric"
  }
 },
 {
  "pkg": "statsig",
  "mod": "index/metricSource",
  "fqn": "pulumi_statsig",
  "classes": {
   "statsig:index/metricSource:MetricSource": "MetricSource"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "statsig",
  "token": "pulumi:providers:statsig",
  "fqn": "pulumi_statsig",
  "class": "Provider"
 }
]
"""
)
